import { defineConfig } from "@playwright/test";

const PORT = 8499;

export default defineConfig({
  testDir: "tests/e2e",
  // *.e2e.ts so `bun test` (which auto-collects *.spec.ts) never picks these up
  testMatch: /.*\.e2e\.ts/,
  // Fixtures are generated by the webServer command itself (Playwright starts
  // the webServer BEFORE globalSetup would run).
  // The app server holds shared state (whisper queue, fake anki map) — run serially.
  fullyParallel: false,
  workers: 1,
  timeout: 60_000,
  expect: { timeout: 10_000 },
  reporter: [["list"]],
  use: {
    baseURL: `http://localhost:${PORT}`,
    launchOptions: {
      args: ["--autoplay-policy=no-user-gesture-required"],
    },
  },
  webServer: {
    command: "bun run tests/e2e/global-setup.ts && bun run src/cli.ts tests/e2e/fixtures/lib",
    url: `http://localhost:${PORT}/api/library`,
    reuseExistingServer: false,
    env: {
      PORT: String(PORT),
      ZR_NO_OPEN: "1",
      GEMINI_FAKE: "1",
      WHISPER_FAKE: "1",
      ANKI_FAKE: "1",
      // Isolate telemetry + settings from the user's real files; the fixtures
      // lib dir is recreated by global-setup, so these reset every run.
      ZR_EVENTS_FILE: "tests/e2e/fixtures/lib/.zr/events.jsonl",
      ZR_CONFIG_DIR: "tests/e2e/fixtures/lib/.zr/config",
    },
  },
});
