// Japanese pitch-accent lookup + pattern computation.
// public/accents.json (generated by scripts/gen-accent.ts from Kanjium data)
// maps "surface|reading" → accent number, plus "reading" alone for kana words.
// Accent number n: 0 = heiban (no drop), 1 = atamadaka (drop after mora 1),
// n>=2 = nakadaka/odaka (drop after mora n).

let accentPromise: Promise<Map<string, number>> | null = null;

export function loadAccents(): Promise<Map<string, number>> {
  if (!accentPromise) {
    accentPromise = fetch("/accents.json")
      .then((r) => {
        if (!r.ok) throw new Error(`accents.json → ${r.status}`);
        return r.json() as Promise<Record<string, number>>;
      })
      .then((obj) => new Map(Object.entries(obj)))
      .catch((e) => {
        accentPromise = null; // allow a retry on transient failure
        throw e;
      });
  }
  return accentPromise;
}

/** katakana → hiragana (keeps ー etc. as-is). */
export function kataToHira(s: string): string {
  let out = "";
  for (const ch of s) {
    const c = ch.codePointAt(0)!;
    out += c >= 0x30a1 && c <= 0x30f6 ? String.fromCodePoint(c - 0x60) : ch;
  }
  return out;
}

/**
 * Pitch accent for a word, or null if unknown.
 *
 * Lookup order (mirrors freqRankOf's basic_form-first logic):
 *   1. `dictForm|reading` — only matches when the reading is the dictionary
 *      form's reading (i.e. unconjugated surface). For conjugated tokens the
 *      caller should pass the dict-form reading if it has one; otherwise the
 *      lookup falls through (kuromoji's `reading` is of the surface).
 *   2. `surface|reading` — exact surface match.
 *   3. `reading` alone — kana-only words (data has reading-only keys).
 * Readings are hiragana-normalized before lookup (tokenizer emits katakana).
 */
export function accentOf(
  accents: Map<string, number>,
  surface: string,
  readingKana: string,
  dictForm?: string,
): number | null {
  const reading = kataToHira(readingKana);
  if (dictForm && dictForm !== "*" && dictForm !== surface) {
    const r = accents.get(`${dictForm}|${reading}`);
    if (r != null) return r;
  }
  return (
    accents.get(`${surface}|${reading}`) ??
    accents.get(reading) ??
    accents.get(kataToHira(surface)) ??
    null
  );
}

const SMALL_KANA = new Set("ぁぃぅぇぉゃゅょゎァィゥェォャュョヮ");

/**
 * Split a kana reading into morae: a small kana (ゃゅょ etc.) attaches to the
 * previous kana; ー, っ, ん each count as their own mora.
 */
export function morae(reading: string): string[] {
  const out: string[] = [];
  for (const ch of reading) {
    if (SMALL_KANA.has(ch) && out.length > 0) out[out.length - 1] += ch;
    else out.push(ch);
  }
  return out;
}

/**
 * Per-mora high/low pattern for a reading and accent number.
 * Standard Tokyo-dialect rules:
 *   accent 0 (heiban):  L H H H ... (low first mora, high from mora 2, no drop)
 *   accent 1 (atamadaka): H L L L ... (high first mora, drop after it)
 *   accent n>=2:        L H..H(n) L ... (rise at mora 2, high through mora n,
 *                       drop after mora n — draw ꜜ after mora n)
 * One-mora words: accent 0 → [true]? No — heiban single mora is low in
 * isolation but rises on the particle; we render it low ([false]).
 * Returns booleans, true = high.
 */
export function accentPattern(reading: string, accent: number): boolean[] {
  const n = morae(kataToHira(reading)).length;
  const out: boolean[] = new Array(n);
  for (let i = 0; i < n; i++) {
    const mora = i + 1;
    if (accent === 0) out[i] = mora >= 2;
    else if (accent === 1) out[i] = mora === 1;
    else out[i] = mora >= 2 && mora <= accent;
  }
  return out;
}
